import { useEffect, useMemo, useRef, useState } from "react";
import { createPlan, deletePlan, getPlanes, updatePlan } from "../../services/api.service";
import { getCodigosOperativos, type CodigoOperativo } from "../../services/codigoOperativo.service";
import { getPlanTarifas, replacePlanTarifas, type PlanTarifa } from "../../services/planTarifa.service";
import PlanImage from "../common/PlanImage";
import "../../styles/planes.css";
import "../../styles/planes-tarifas.css";
import { supabase } from "../../lib/supabase";
import { Plus, Pencil, Trash2, Eye, Package, Search, X, ChevronLeft, ChevronRight, RefreshCw, Upload, Calendar, Clock, Trash, Users, BadgeDollarSign, Layers3, CarFront } from "lucide-react";

interface PlanFecha { id_fecha?: number; id_plan?: number; fecha: string; }
interface PlanHora { id_hora?: number; id_plan?: number; hora: string; }
interface Plan {
  id_plan: number;
  nombre_plan: string;
  codigo_plan?: string | null;
  precio_plan?: number | null;
  descripcion_basica?: string | null;
  descripcion_detallada?: string | null;
  imagen_url?: string | null;
  numero_plan?: number | null;
  tipo_fecha: "cualquier_dia" | "fechas_especificas";
  tipo_hora: "sin_hora" | "hora_fija" | "varias_horas";
  id_plan_padre?: number | null;
  es_grupo?: boolean;
  activo?: boolean;
  plan_fechas?: PlanFecha[];
  plan_horas?: PlanHora[];
}

type PlanKind = "normal" | "grupo" | "subplan";
type PlanForm = Omit<Plan, "id_plan" | "codigo_plan">;
type TarifaForm = { semana1:number|null; semana23:number|null; semana4:number|null; finSemana:number|null; buggy1:number|null; buggy2:number|null };

const emptyPlan:PlanForm={nombre_plan:"",precio_plan:null,descripcion_basica:null,descripcion_detallada:null,imagen_url:null,numero_plan:null,tipo_fecha:"cualquier_dia",tipo_hora:"sin_hora",id_plan_padre:null,es_grupo:false,activo:true,plan_fechas:[],plan_horas:[]};
const emptyTarifas:TarifaForm={semana1:null,semana23:null,semana4:null,finSemana:null,buggy1:null,buggy2:null};
const PAGE_SIZE_OPTIONS=[10,25,50];
const fmtPrecio=(v?:number|null)=>v==null?"—":"$"+Number(v).toLocaleString("es-CO");
const numOrNull=(v:string)=>v===""?null:Number(v.replace(/[^0-9]/g,""));

export default function PlanesAdmin(){
  const[planes,setPlanes]=useState<Plan[]>([]),[codigos,setCodigos]=useState<CodigoOperativo[]>([]),[tarifas,setTarifas]=useState<PlanTarifa[]>([]),[loading,setLoading]=useState(true);
  const[search,setSearch]=useState(""),[pageSize,setPageSize]=useState(10),[page,setPage]=useState(1);
  const[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<Plan|null>(null),[viewing,setViewing]=useState<Plan|null>(null),[formData,setFormData]=useState<PlanForm>(emptyPlan),[kind,setKind]=useState<PlanKind>("normal"),[tarifaForm,setTarifaForm]=useState<TarifaForm>(emptyTarifas),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
  const fileInputRef=useRef<HTMLInputElement>(null);

  const fetchData=async()=>{try{setLoading(true);const[p,c,t]=await Promise.all([getPlanes(),getCodigosOperativos(),getPlanTarifas()]);setPlanes(p as Plan[]);setCodigos(c);setTarifas(t)}catch(e){console.error(e)}finally{setLoading(false)}};
  useEffect(()=>{fetchData()},[]);
  useEffect(()=>{if(!supabase)return;const ch=supabase.channel("planes-admin").on("postgres_changes",{event:"*",schema:"public",table:"plan"},fetchData).on("postgres_changes",{event:"*",schema:"public",table:"plan_tarifa"},fetchData).on("postgres_changes",{event:"*",schema:"public",table:"codigo_operativo"},fetchData).subscribe();return()=>{supabase?.removeChannel(ch)}},[]);

  const grupos=useMemo(()=>planes.filter(p=>p.es_grupo),[planes]);
  const hijosPorPadre=useMemo(()=>{const m=new Map<number,Plan[]>();for(const p of planes){if(!p.id_plan_padre)continue;if(!m.has(p.id_plan_padre))m.set(p.id_plan_padre,[]);m.get(p.id_plan_padre)!.push(p)}return m},[planes]);
  const codesFor=(id:number)=>codigos.filter(c=>Number(c.id_plan)===Number(id)).sort((a,b)=>a.codigo_ch.localeCompare(b.codigo_ch));
  const tariffsFor=(id:number)=>tarifas.filter(t=>Number(t.id_plan)===Number(id));
  const tarifaBy=(id:number,tipo:string,min:number,max:number|null)=>tariffsFor(id).find(t=>t.tipo_dia===tipo&&t.personas_min===min&&(t.personas_max??null)===max)?.precio_persona??null;
  const kindOf=(p:Plan):PlanKind=>p.es_grupo?"grupo":p.id_plan_padre?"subplan":"normal";
  const parentName=(p:Plan)=>p.id_plan_padre?planes.find(x=>x.id_plan===p.id_plan_padre)?.nombre_plan:null;
  const buggyTotal=(p:Plan,cantidad:1|2)=>{const unit=tarifaBy(p.id_plan,"todos",cantidad,cantidad);return unit==null?null:unit*cantidad};

  const openCreate=(preset:PlanKind="normal")=>{setEditing(null);setKind(preset);setFormData({...emptyPlan,es_grupo:preset==="grupo",id_plan_padre:preset==="subplan"?(grupos[0]?.id_plan??null):null});setTarifaForm(emptyTarifas);setShowForm(true)};
  const openEdit=(p:Plan)=>{const k=kindOf(p);setEditing(p);setKind(k);setFormData({nombre_plan:p.nombre_plan,precio_plan:p.precio_plan??null,descripcion_basica:p.descripcion_basica??null,descripcion_detallada:p.descripcion_detallada??null,imagen_url:p.imagen_url??null,numero_plan:p.numero_plan??null,tipo_fecha:p.tipo_fecha||"cualquier_dia",tipo_hora:p.tipo_hora||"sin_hora",id_plan_padre:p.id_plan_padre??null,es_grupo:!!p.es_grupo,activo:p.activo!==false,plan_fechas:p.plan_fechas||[],plan_horas:p.plan_horas||[]});const fallback=p.precio_plan??null;setTarifaForm({semana1:tarifaBy(p.id_plan,"semana",1,1)??fallback,semana23:tarifaBy(p.id_plan,"semana",2,3)??fallback,semana4:tarifaBy(p.id_plan,"semana",4,null)??fallback,finSemana:tarifaBy(p.id_plan,"fin_semana",1,null)??fallback,buggy1:buggyTotal(p,1),buggy2:buggyTotal(p,2)});setShowForm(true)};

  const setPlanKind=(next:PlanKind)=>{setKind(next);setFormData(p=>({...p,es_grupo:next==="grupo",id_plan_padre:next==="subplan"?(p.id_plan_padre??grupos[0]?.id_plan??null):null,precio_plan:next==="grupo"?null:p.precio_plan,tipo_fecha:next==="grupo"?"cualquier_dia":p.tipo_fecha,tipo_hora:next==="grupo"?"sin_hora":p.tipo_hora,plan_fechas:next==="grupo"?[]:p.plan_fechas,plan_horas:next==="grupo"?[]:p.plan_horas}));setTarifaForm(emptyTarifas)};

  const handleFileUpload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!supabase)return;setUploading(true);try{const ext=file.name.split(".").pop();const name=`${Math.random().toString(36).slice(2)}-${Date.now()}.${ext}`;const{error}=await supabase.storage.from("planes").upload(name,file,{cacheControl:"3600",upsert:false});if(error)throw error;const{data}=supabase.storage.from("planes").getPublicUrl(name);setFormData(p=>({...p,imagen_url:data.publicUrl}))}catch(e:any){alert(e?.message||"No se pudo subir la imagen.")}finally{setUploading(false)}};

  const validate=()=>{
    if(!formData.nombre_plan.trim()){alert("El nombre del plan es obligatorio.");return false}
    if(kind==="subplan"&&!formData.id_plan_padre){alert("Selecciona el grupo principal al que pertenece este subplan.");return false}
    if(kind==="normal"&&formData.tipo_fecha==="cualquier_dia"&&[tarifaForm.semana1,tarifaForm.semana23,tarifaForm.semana4,tarifaForm.finSemana].some(v=>v==null||Number(v)<=0)){alert("Registra las cuatro tarifas del plan: 1 persona, 2–3, 4+ y fin de semana.");return false}
    if(kind==="normal"&&formData.tipo_fecha==="fechas_especificas"&&(formData.precio_plan==null||Number(formData.precio_plan)<=0)){alert("Registra el precio por persona del plan para las fechas específicas.");return false}
    if(kind==="subplan"&&[tarifaForm.buggy1,tarifaForm.buggy2].some(v=>v==null||Number(v)<=0)){alert("Registra el valor total de 1 persona / 1 Buggy y 2 personas / 1 Buggy.");return false}
    if(kind!=="grupo"&&formData.tipo_fecha==="fechas_especificas"&&!formData.plan_fechas?.length){alert("Agrega al menos una fecha.");return false}
    if(kind!=="grupo"&&formData.tipo_hora==="hora_fija"&&formData.plan_horas?.length!==1){alert("Agrega una hora fija.");return false}
    if(kind!=="grupo"&&formData.tipo_hora==="varias_horas"&&!formData.plan_horas?.length){alert("Agrega al menos una hora.");return false}
    return true;
  };

  const handleSave=async()=>{if(!validate())return;setSaving(true);try{
    let precioBase: number|null=formData.precio_plan??null;
    if(kind==="normal"&&formData.tipo_fecha==="cualquier_dia")precioBase=tarifaForm.finSemana;
    if(kind==="subplan")precioBase=tarifaForm.buggy1;
    if(kind==="grupo")precioBase=null;
    const payload={...formData,es_grupo:kind==="grupo",id_plan_padre:kind==="subplan"?formData.id_plan_padre:null,precio_plan:precioBase,plan_fechas:kind!=="grupo"&&formData.tipo_fecha==="fechas_especificas"?formData.plan_fechas:[],plan_horas:kind!=="grupo"&&formData.tipo_hora!=="sin_hora"?formData.plan_horas:[]};
    const saved=editing?await updatePlan(editing.id_plan,payload):await createPlan(payload);
    if(kind==="grupo")await replacePlanTarifas(saved.id_plan,[]);
    else if(kind==="subplan")await replacePlanTarifas(saved.id_plan,[{personas_min:1,personas_max:1,precio_persona:Number(tarifaForm.buggy1),tipo_dia:"todos",activo:true},{personas_min:2,personas_max:2,precio_persona:Number(tarifaForm.buggy2)/2,tipo_dia:"todos",activo:true}]);
    else if(formData.tipo_fecha==="cualquier_dia")await replacePlanTarifas(saved.id_plan,[{personas_min:1,personas_max:1,precio_persona:Number(tarifaForm.semana1),tipo_dia:"semana",activo:true},{personas_min:2,personas_max:3,precio_persona:Number(tarifaForm.semana23),tipo_dia:"semana",activo:true},{personas_min:4,personas_max:null,precio_persona:Number(tarifaForm.semana4),tipo_dia:"semana",activo:true},{personas_min:1,personas_max:null,precio_persona:Number(tarifaForm.finSemana),tipo_dia:"fin_semana",activo:true}]);
    else await replacePlanTarifas(saved.id_plan,[]);
    setShowForm(false);await fetchData();
  }catch(e:any){console.error(e);alert(e?.message||"Ocurrió un error al guardar el plan.")}finally{setSaving(false)}};

  const handleDelete=async(p:Plan)=>{if(p.es_grupo&&(hijosPorPadre.get(p.id_plan)?.length||0)>0){alert("Este grupo todavía tiene subplanes. Reasigna o elimina primero sus rutas.");return}if(!confirm(`¿Eliminar \"${p.nombre_plan}\"?`))return;try{await deletePlan(p.id_plan);await fetchData()}catch(e:any){alert(e?.message||"No se pudo eliminar el plan.")}};

  const filtered=planes.filter(p=>{const q=search.toLowerCase().trim();const ch=codesFor(p.id_plan).map(c=>`${c.codigo_ch} ${c.descripcion}`).join(" ").toLowerCase();return !q||p.nombre_plan.toLowerCase().includes(q)||(p.descripcion_basica??"").toLowerCase().includes(q)||String(p.numero_plan??"").includes(q)||ch.includes(q)});
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const paginated=filtered.slice((page-1)*pageSize,page*pageSize);
  const planesConCodigo=planes.filter(p=>codesFor(p.id_plan).some(c=>c.activo)).length;

  const PriceSummary=({plan}:{plan:Plan})=>{const k=kindOf(plan);if(k==="grupo")return <div className="plan-price-summary"><strong>Grupo</strong><small>{hijosPorPadre.get(plan.id_plan)?.length||0} rutas configuradas</small></div>;if(k==="subplan"){return <div className="plan-price-summary"><strong>1 persona {fmtPrecio(buggyTotal(plan,1))}</strong><small>2 personas · 1 Buggy {fmtPrecio(buggyTotal(plan,2))}</small></div>}const ts=tariffsFor(plan.id_plan);if(plan.tipo_fecha!=="cualquier_dia"||!ts.length)return <span>{fmtPrecio(plan.precio_plan)}</span>;return <div className="plan-price-summary"><strong>Finde {fmtPrecio(tarifaBy(plan.id_plan,"fin_semana",1,null))}</strong><small>L–V: 1p {fmtPrecio(tarifaBy(plan.id_plan,"semana",1,1))} · 2–3p {fmtPrecio(tarifaBy(plan.id_plan,"semana",2,3))} · 4+p {fmtPrecio(tarifaBy(plan.id_plan,"semana",4,null))}</small></div>};
  const Codes=({plan}:{plan:Plan})=>{const list=codesFor(plan.id_plan);return list.length?<div className="code-list">{list.map(c=><span key={c.id_codigo_operativo} className="badge badge-blue">{c.codigo_ch}</span>)}</div>:<span className="rv-null">—</span>};

  return <div className="planes-page">
    <div className="planes-header"><div><h1 className="planes-title">Planes</h1><p className="planes-subtitle">Planes, grupos, subplanes, tarifas, precios y disponibilidad.</p></div><div className="planes-header-actions"><button className="btn-secondary-plan" onClick={()=>openCreate("grupo")}><Layers3 size={16}/> Nuevo grupo</button><button className="btn-nuevo-plan" onClick={()=>openCreate("normal")}><Plus size={16}/> Nuevo plan</button></div></div>
    <div className="planes-kpis"><div className="kpi-card line-blue"><div className="kpi-icon"><Package size={24}/></div><div className="kpi-info"><h3>{planes.filter(p=>!p.es_grupo).length}</h3><p>Planes vendibles</p></div></div><div className="kpi-card line-green"><div className="kpi-icon"><Layers3 size={24}/></div><div className="kpi-info"><h3>{grupos.length}</h3><p>Grupos · {planesConCodigo} planes con CH</p></div></div></div>
    <div className="planes-filter-bar"><div className="planes-search-wrap"><Search size={18} className="planes-search-icon"/><input className="planes-search-input" placeholder="Buscar por CH, nombre o descripción..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><button className="planes-clear-btn" onClick={()=>{setSearch("");setPage(1)}}><X size={14}/> Limpiar</button><span className="planes-rows-label">Filas:</span><select className="planes-rows-select" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{PAGE_SIZE_OPTIONS.map(n=><option key={n}>{n}</option>)}</select><button className="btn-refresh" onClick={fetchData}><RefreshCw size={18}/></button></div>
    <div className="planes-table-wrap"><table className="planes-table"><thead><tr><th>N°</th><th>TIPO</th><th>CÓDIGOS CH</th><th>PLAN / RUTA</th><th>PRECIOS</th><th>FECHA</th><th>HORA</th><th>ACCIONES</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="plan-empty">Cargando...</td></tr>:paginated.length===0?<tr><td colSpan={8} className="plan-empty">Sin resultados</td></tr>:paginated.map(p=>{const k=kindOf(p);return <tr key={p.id_plan} className={k==="grupo"?"plan-group-row":k==="subplan"?"plan-child-row":""}><td>{p.numero_plan??"—"}</td><td><span className={`plan-kind-badge ${k}`}>{k==="grupo"?"Grupo":k==="subplan"?"Subplan":"Plan"}</span></td><td><Codes plan={p}/></td><td><div className="plan-name-cell"><PlanImage src={p.imagen_url} alt={p.nombre_plan} className="plan-thumb"/><div><div className="plan-name">{k==="subplan"&&<span className="child-prefix">↳ </span>}{p.nombre_plan}</div>{k==="subplan"&&<div className="plan-parent-label"><CarFront size={12}/> {parentName(p)}</div>}<div className="plan-desc-short">{p.descripcion_basica??""}</div></div></div></td><td><PriceSummary plan={p}/></td><td>{k==="grupo"?<span className="rv-null">—</span>:p.tipo_fecha==="cualquier_dia"?<span className="badge badge-gray">Cualquier día</span>:<span className="badge badge-yellow">Fechas esp. ({p.plan_fechas?.length||0})</span>}</td><td>{k==="grupo"?<span className="rv-null">—</span>:p.tipo_hora==="sin_hora"?<span className="badge badge-gray">Sin hora</span>:p.tipo_hora==="hora_fija"?<span className="badge badge-blue">Hora fija</span>:<span className="badge badge-teal">Varias ({p.plan_horas?.length||0})</span>}</td><td><div className="action-buttons"><button className="action-btn action-ver" onClick={()=>setViewing(p)}><Eye size={14}/> Ver</button><button className="action-btn action-editar" onClick={()=>openEdit(p)}><Pencil size={14}/> Editar</button>{k==="grupo"&&<button className="action-btn action-editar" onClick={()=>{openCreate("subplan");setFormData(x=>({...x,id_plan_padre:p.id_plan}))}}><Plus size={14}/> Ruta</button>}<button className="action-btn action-eliminar" onClick={()=>handleDelete(p)}><Trash2 size={14}/> Eliminar</button></div></td></tr>})}</tbody></table><div className="planes-pagination"><span>Mostrando {filtered.length===0?0:(page-1)*pageSize+1}–{Math.min(page*pageSize,filtered.length)} de {filtered.length}</span><div className="planes-pag-controls"><button className="planes-pag-btn" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/> Anterior</button><span>Página {page} / {totalPages}</span><button className="planes-pag-btn" disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>Siguiente <ChevronRight size={15}/></button></div></div></div>

    {viewing&&<div className="modal-overlay"><div className="modal-card"><div className="modal-header"><h2>{viewing.es_grupo?"Grupo de planes":"Detalle del plan"}</h2><button className="modal-close" onClick={()=>setViewing(null)}><X size={20}/></button></div><div className="modal-body"><PlanImage src={viewing.imagen_url} alt={viewing.nombre_plan} className="modal-img"/><div className="modal-field"><label>Nombre</label><span>{viewing.nombre_plan}</span></div>{viewing.id_plan_padre&&<div className="modal-field"><label>Grupo</label><span>{parentName(viewing)}</span></div>}<div className="modal-field"><label>Precios</label><PriceSummary plan={viewing}/></div>{viewing.es_grupo&&<div className="modal-field"><label>Rutas</label><div>{(hijosPorPadre.get(viewing.id_plan)||[]).map(h=><div key={h.id_plan} className="group-child-line">{h.nombre_plan} · <PriceSummary plan={h}/></div>)}</div></div>}<div className="modal-field"><label>Descripción</label><span>{viewing.descripcion_detallada||viewing.descripcion_basica||"—"}</span></div></div></div></div>}

    {showForm&&<div className="modal-overlay"><div className="modal-card plan-edit-modal"><div className="modal-header"><h2>{editing?"Editar":"Crear"} {kind==="grupo"?"grupo":kind==="subplan"?"subplan / ruta":"plan"}</h2><button className="modal-close" onClick={()=>!saving&&setShowForm(false)} disabled={saving}><X size={20}/></button></div><div className="modal-body">
      <div className="plan-kind-selector"><button className={kind==="normal"?"active":""} onClick={()=>setPlanKind("normal")} type="button"><Package size={18}/><strong>Plan normal</strong><small>Senderismo y experiencias estándar</small></button><button className={kind==="grupo"?"active":""} onClick={()=>setPlanKind("grupo")} type="button"><Layers3 size={18}/><strong>Grupo</strong><small>Ej. Buggies por Nemocón</small></button><button className={kind==="subplan"?"active":""} onClick={()=>setPlanKind("subplan")} type="button"><CarFront size={18}/><strong>Subplan / ruta</strong><small>Una opción dentro de un grupo</small></button></div>
      {kind==="subplan"&&<div className="form-group plan-parent-select"><label>Grupo principal *</label><select value={formData.id_plan_padre??""} onChange={e=>setFormData({...formData,id_plan_padre:e.target.value?Number(e.target.value):null})}><option value="">Seleccionar grupo</option>{grupos.filter(g=>!editing||g.id_plan!==editing.id_plan).map(g=><option key={g.id_plan} value={g.id_plan}>{g.nombre_plan}</option>)}</select></div>}
      <div className="form-group"><label>Nombre *</label><input value={formData.nombre_plan} onChange={e=>setFormData({...formData,nombre_plan:e.target.value})} placeholder={kind==="grupo"?"Ej. Buggies por Nemocón":kind==="subplan"?"Ej. Mirador del Desierto":"Nombre del plan"}/></div>
      <div className="form-row"><div className="form-group"><label>N° de plan</label><input type="number" value={formData.numero_plan??""} onChange={e=>setFormData({...formData,numero_plan:e.target.value?Number(e.target.value):null})} placeholder={kind==="grupo"?"6":"Opcional"}/></div><div className="form-group"><label>Estado</label><select value={formData.activo===false?"0":"1"} onChange={e=>setFormData({...formData,activo:e.target.value==="1"})}><option value="1">Activo</option><option value="0">Inactivo</option></select></div></div>
      <div className="form-group"><label>Descripción básica</label><textarea rows={3} value={formData.descripcion_basica??""} onChange={e=>setFormData({...formData,descripcion_basica:e.target.value||null})}/></div><div className="form-group"><label>Descripción detallada</label><textarea rows={4} value={formData.descripcion_detallada??""} onChange={e=>setFormData({...formData,descripcion_detallada:e.target.value||null})}/></div>

      {kind==="normal"&&formData.tipo_fecha==="cualquier_dia"&&<section className="tarifa-builder"><div className="tarifa-builder-head"><div className="tarifa-builder-icon"><BadgeDollarSign size={20}/></div><div><strong>Tarifas automáticas por cantidad</strong><small>Lunes a viernes cambia por cantidad; sábado y domingo usan tarifa normal.</small></div></div><div className="tarifa-grid">{([["semana1","Lunes a viernes · 1 persona"],["semana23","Lunes a viernes · 2 o 3"],["semana4","Lunes a viernes · 4 o más"],["finSemana","Sábado y domingo · precio normal"]] as const).map(([key,label])=><label key={key}><span><Users size={14}/> {label}</span><div className="money-input"><b>$</b><input inputMode="numeric" value={tarifaForm[key]??""} onChange={e=>setTarifaForm({...tarifaForm,[key]:numOrNull(e.target.value)})}/></div></label>)}</div></section>}

      {kind==="normal"&&formData.tipo_fecha==="fechas_especificas"&&<section className="tarifa-builder"><div className="tarifa-builder-head"><div className="tarifa-builder-icon"><BadgeDollarSign size={20}/></div><div><strong>Precio del plan</strong><small>Este valor se cobrará por persona en las fechas específicas configuradas.</small></div></div><div className="tarifa-grid"><label><span><Users size={14}/> Precio por persona *</span><div className="money-input"><b>$</b><input inputMode="numeric" value={formData.precio_plan??""} onChange={e=>setFormData({...formData,precio_plan:numOrNull(e.target.value)})} placeholder="Ej. 220000"/></div></label></div></section>}

      {kind==="subplan"&&<section className="tarifa-builder buggy-tarifa-builder"><div className="tarifa-builder-head"><div className="tarifa-builder-icon"><CarFront size={20}/></div><div><strong>Tarifa de esta ruta</strong><small>El valor es por 1 Buggy completo, no se multiplica nuevamente por persona.</small></div></div><div className="tarifa-grid buggy-grid"><label><span>👤 1 persona · 1 Buggy</span><div className="money-input"><b>$</b><input inputMode="numeric" value={tarifaForm.buggy1??""} onChange={e=>setTarifaForm({...tarifaForm,buggy1:numOrNull(e.target.value)})} placeholder="76000"/></div></label><label><span>👥 2 personas · 1 Buggy</span><div className="money-input"><b>$</b><input inputMode="numeric" value={tarifaForm.buggy2??""} onChange={e=>setTarifaForm({...tarifaForm,buggy2:numOrNull(e.target.value)})} placeholder="95000"/></div></label></div><div className="tarifa-example">Ejemplo: si registras $95.000 para 2 personas, la reserva total será <strong>$95.000</strong>, no $190.000.</div></section>}

      {kind!=="grupo"&&<><div className="form-section"><h3 className="section-title">Disponibilidad de fecha</h3><div className="radio-group"><label className="radio-label"><input type="radio" checked={formData.tipo_fecha==="cualquier_dia"} onChange={()=>setFormData({...formData,tipo_fecha:"cualquier_dia",plan_fechas:[]})}/><span>Cualquier día</span></label><label className="radio-label"><input type="radio" checked={formData.tipo_fecha==="fechas_especificas"} onChange={()=>setFormData({...formData,tipo_fecha:"fechas_especificas"})}/><span>Fechas específicas</span></label></div>{formData.tipo_fecha==="fechas_especificas"&&<div className="dynamic-list">{formData.plan_fechas?.map((f,i)=><div className="dynamic-item" key={i}><Calendar size={16}/><input type="date" value={f.fecha} onChange={e=>{const n=[...(formData.plan_fechas||[])];n[i]={...n[i],fecha:e.target.value};setFormData({...formData,plan_fechas:n})}}/><button type="button" className="btn-remove-item" onClick={()=>setFormData({...formData,plan_fechas:formData.plan_fechas?.filter((_,x)=>x!==i)})}><Trash size={14}/></button></div>)}<button type="button" className="btn-add-item" onClick={()=>setFormData({...formData,plan_fechas:[...(formData.plan_fechas||[]),{fecha:""}]})}><Plus size={14}/> Agregar fecha</button></div>}</div>
      <div className="form-section"><h3 className="section-title">Disponibilidad de hora</h3><div className="radio-group"><label className="radio-label"><input type="radio" checked={formData.tipo_hora==="sin_hora"} onChange={()=>setFormData({...formData,tipo_hora:"sin_hora",plan_horas:[]})}/><span>Sin hora</span></label><label className="radio-label"><input type="radio" checked={formData.tipo_hora==="hora_fija"} onChange={()=>setFormData({...formData,tipo_hora:"hora_fija",plan_horas:formData.plan_horas?.length?[formData.plan_horas[0]]:[{hora:""}]})}/><span>Hora fija</span></label><label className="radio-label"><input type="radio" checked={formData.tipo_hora==="varias_horas"} onChange={()=>setFormData({...formData,tipo_hora:"varias_horas"})}/><span>Varias horas</span></label></div>{formData.tipo_hora!=="sin_hora"&&<div className="dynamic-list">{formData.plan_horas?.map((h,i)=><div className="dynamic-item" key={i}><Clock size={16}/><input type="time" value={h.hora} onChange={e=>{const n=[...(formData.plan_horas||[])];n[i]={...n[i],hora:e.target.value};setFormData({...formData,plan_horas:n})}}/>{formData.tipo_hora==="varias_horas"&&<button type="button" className="btn-remove-item" onClick={()=>setFormData({...formData,plan_horas:formData.plan_horas?.filter((_,x)=>x!==i)})}><Trash size={14}/></button>}</div>)}{formData.tipo_hora==="varias_horas"&&<button type="button" className="btn-add-item" onClick={()=>setFormData({...formData,plan_horas:[...(formData.plan_horas||[]),{hora:""}]})}><Plus size={14}/> Agregar hora</button>}</div>}</div></>}

      <div className="form-group"><label>Imagen</label><div className="image-upload-container">{formData.imagen_url?<div className="image-preview-wrap"><PlanImage src={formData.imagen_url} alt="Preview" className="image-preview"/><button type="button" className="btn-remove-image" onClick={()=>setFormData({...formData,imagen_url:null})}><X size={14}/></button></div>:<button type="button" className="btn-upload-placeholder" onClick={()=>fileInputRef.current?.click()} disabled={uploading}>{uploading?<RefreshCw size={24}/>:<><Upload size={24}/><span>Subir imagen</span></>}</button>}<input type="file" ref={fileInputRef} onChange={handleFileUpload} accept="image/*" style={{display:"none"}}/></div></div><div className="form-group"><label>O URL de imagen</label><input value={formData.imagen_url??""} onChange={e=>setFormData({...formData,imagen_url:e.target.value||null})}/></div>
    </div><div className="modal-footer"><button className="btn-cancelar" onClick={()=>!saving&&setShowForm(false)} disabled={saving}>Cancelar</button><button className="btn-guardar" onClick={handleSave} disabled={saving}>{saving?"Guardando...":editing?"Guardar cambios":kind==="grupo"?"Crear grupo":kind==="subplan"?"Crear ruta":"Crear plan"}</button></div></div></div>}
  </div>;
}
