-- Adicionales configurables por plan y reserva
-- Ejecutar en Supabase SQL Editor del proyecto de pagina.admnins.
-- Diseñado para convivir con precio_plan / plan_tarifa y con la lógica CH existente.

create table if not exists public.adicional (
  id_adicional bigint generated by default as identity primary key,
  codigo text not null unique check (codigo ~ '^[a-z0-9_]+$'),
  nombre text not null,
  descripcion text,
  precio numeric(12,2) not null default 0 check (precio >= 0),
  tipo_cobro text not null default 'por_persona'
    check (tipo_cobro in ('por_persona', 'por_reserva')),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_adicional (
  id_plan integer not null references public.plan(id_plan) on delete cascade,
  id_adicional bigint not null references public.adicional(id_adicional) on delete restrict,
  modalidad text not null
    check (modalidad in ('opcional', 'incluido')),
  precio_override numeric(12,2) check (precio_override is null or precio_override >= 0),
  permitir_quitar boolean not null default false,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plan_adicional_pkey primary key (id_plan, id_adicional),
  constraint plan_adicional_quitar_check
    check (modalidad = 'incluido' or permitir_quitar = false)
);

create table if not exists public.reserva_adicional (
  id_reserva_adicional bigint generated by default as identity primary key,
  id_reserva integer not null references public.reserva(id_reserva) on delete cascade,
  id_adicional bigint references public.adicional(id_adicional) on delete restrict,
  codigo_adicional text not null,
  nombre_adicional text not null,
  tipo_cobro text not null
    check (tipo_cobro in ('por_persona', 'por_reserva')),
  tipo_movimiento text not null
    check (tipo_movimiento in ('agregado', 'incluido', 'retirado')),
  precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
  cantidad_aplicada integer not null default 1 check (cantidad_aplicada >= 1),
  impacto_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  constraint reserva_adicional_unico unique (id_reserva, id_adicional)
);

create index if not exists idx_plan_adicional_plan on public.plan_adicional(id_plan);
create index if not exists idx_plan_adicional_adicional on public.plan_adicional(id_adicional);
create index if not exists idx_reserva_adicional_reserva on public.reserva_adicional(id_reserva);
create index if not exists idx_adicional_activo on public.adicional(activo);

insert into public.adicional (codigo, nombre, descripcion, precio, tipo_cobro, activo)
values
  ('almuerzo', 'Almuerzo', 'Almuerzo adicional por persona.', 0, 'por_persona', true),
  ('transporte', 'Transporte', 'Transporte adicional configurable por plan.', 0, 'por_persona', true)
on conflict (codigo) do nothing;

alter table public.adicional enable row level security;
alter table public.plan_adicional enable row level security;
alter table public.reserva_adicional enable row level security;

revoke all on table public.adicional from anon, authenticated;
revoke all on table public.plan_adicional from anon, authenticated;
revoke all on table public.reserva_adicional from anon, authenticated;

grant select, insert, update, delete on table public.adicional to authenticated;
grant select, insert, update, delete on table public.plan_adicional to authenticated;
grant select, insert, update, delete on table public.reserva_adicional to authenticated;

grant usage, select on sequence public.adicional_id_adicional_seq to authenticated;
grant usage, select on sequence public.reserva_adicional_id_reserva_adicional_seq to authenticated;

drop policy if exists adicional_select_staff on public.adicional;
create policy adicional_select_staff on public.adicional
for select to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

drop policy if exists adicional_admin_insert on public.adicional;
create policy adicional_admin_insert on public.adicional
for insert to authenticated
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists adicional_admin_update on public.adicional;
create policy adicional_admin_update on public.adicional
for update to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
)
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists adicional_admin_delete on public.adicional;
create policy adicional_admin_delete on public.adicional
for delete to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists plan_adicional_select_staff on public.plan_adicional;
create policy plan_adicional_select_staff on public.plan_adicional
for select to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

drop policy if exists plan_adicional_admin_insert on public.plan_adicional;
create policy plan_adicional_admin_insert on public.plan_adicional
for insert to authenticated
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists plan_adicional_admin_update on public.plan_adicional;
create policy plan_adicional_admin_update on public.plan_adicional
for update to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
)
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists plan_adicional_admin_delete on public.plan_adicional;
create policy plan_adicional_admin_delete on public.plan_adicional
for delete to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre = 'administrador'
  )
);

drop policy if exists reserva_adicional_select_staff on public.reserva_adicional;
create policy reserva_adicional_select_staff on public.reserva_adicional
for select to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

drop policy if exists reserva_adicional_staff_insert on public.reserva_adicional;
create policy reserva_adicional_staff_insert on public.reserva_adicional
for insert to authenticated
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

drop policy if exists reserva_adicional_staff_update on public.reserva_adicional;
create policy reserva_adicional_staff_update on public.reserva_adicional
for update to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
)
with check (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

drop policy if exists reserva_adicional_staff_delete on public.reserva_adicional;
create policy reserva_adicional_staff_delete on public.reserva_adicional
for delete to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);
