-- Planes adicionales por reserva
-- IMPORTANTE: este módulo es distinto al catálogo "adicional" y a la relación "plan_adicional".
-- Aquí se guarda cuando una reserva ya creada agrega otro PLAN o un ADICIONAL como una compra extra.

create table if not exists public.reserva_plan_adicional (
  id_reserva_plan_adicional bigint generated by default as identity primary key,
  id_reserva integer not null references public.reserva(id_reserva) on delete cascade,
  origen text not null check (origen in ('plan', 'adicional')),
  id_plan_adicional integer references public.plan(id_plan) on delete restrict,
  id_adicional bigint references public.adicional(id_adicional) on delete restrict,
  nombre text not null,
  tipo_cobro text not null check (tipo_cobro in ('por_persona', 'por_reserva')),
  precio_unitario numeric(12,2) not null default 0 check (precio_unitario >= 0),
  cantidad_personas integer not null default 1 check (cantidad_personas >= 1),
  aplica_todos boolean not null default true,
  impacto_total numeric(12,2) not null default 0 check (impacto_total >= 0),
  activo boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  removed_by uuid,
  removed_at timestamptz
);

-- La restricción se administra fuera del CREATE TABLE para que el script
-- pueda ejecutarse varias veces sin fallar si la tabla ya existe.
alter table public.reserva_plan_adicional
  drop constraint if exists reserva_plan_adicional_origen_check;

alter table public.reserva_plan_adicional
  add constraint reserva_plan_adicional_origen_check
  check (
    (origen = 'plan' and id_plan_adicional is not null and id_adicional is null)
    or
    (origen = 'adicional' and id_adicional is not null and id_plan_adicional is null)
  );

create index if not exists idx_reserva_plan_adicional_reserva
  on public.reserva_plan_adicional(id_reserva);

create index if not exists idx_reserva_plan_adicional_activo
  on public.reserva_plan_adicional(id_reserva, activo);

create unique index if not exists uq_reserva_plan_adicional_plan_activo
  on public.reserva_plan_adicional(id_reserva, id_plan_adicional)
  where activo = true and origen = 'plan';

create unique index if not exists uq_reserva_plan_adicional_adicional_activo
  on public.reserva_plan_adicional(id_reserva, id_adicional)
  where activo = true and origen = 'adicional';

alter table public.reserva_plan_adicional enable row level security;

revoke all on table public.reserva_plan_adicional from anon, authenticated;
grant select on table public.reserva_plan_adicional to authenticated;

drop policy if exists reserva_plan_adicional_select_staff on public.reserva_plan_adicional;
create policy reserva_plan_adicional_select_staff on public.reserva_plan_adicional
for select to authenticated
using (
  exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = (select auth.uid())
      and r.nombre in ('administrador', 'atencion')
  )
);

create or replace function public.agregar_plan_adicional_reserva(
  p_id_reserva integer,
  p_origen text,
  p_id_plan_adicional integer,
  p_id_adicional bigint,
  p_nombre text,
  p_tipo_cobro text,
  p_precio_unitario numeric,
  p_cantidad_personas integer,
  p_aplica_todos boolean,
  p_impacto_total numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
  v_total_actual numeric(12,2);
  v_nuevo_total numeric(12,2);
begin
  if not exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = auth.uid()
      and r.nombre in ('administrador', 'atencion')
  ) then
    raise exception 'No autorizado para agregar planes adicionales.';
  end if;

  if p_origen not in ('plan', 'adicional') then
    raise exception 'Origen de plan adicional inválido.';
  end if;

  if p_tipo_cobro not in ('por_persona', 'por_reserva') then
    raise exception 'Tipo de cobro inválido.';
  end if;

  if coalesce(p_cantidad_personas, 0) < 1 then
    raise exception 'La cantidad de personas debe ser mayor a cero.';
  end if;

  if coalesce(p_impacto_total, 0) <= 0 then
    raise exception 'El valor a sumar debe ser mayor a cero.';
  end if;

  if p_origen = 'plan' and p_id_plan_adicional is null then
    raise exception 'Debe indicar el plan adicional.';
  end if;

  if p_origen = 'adicional' and p_id_adicional is null then
    raise exception 'Debe indicar el adicional.';
  end if;

  select coalesce(
    r.valor_total,
    coalesce(r.precio_unitario, 0) * greatest(coalesce(r.cantidad_personas, 1), 1),
    0
  )
  into v_total_actual
  from public.reserva r
  where r.id_reserva = p_id_reserva
  for update;

  if not found then
    raise exception 'La reserva no existe.';
  end if;

  insert into public.reserva_plan_adicional (
    id_reserva,
    origen,
    id_plan_adicional,
    id_adicional,
    nombre,
    tipo_cobro,
    precio_unitario,
    cantidad_personas,
    aplica_todos,
    impacto_total,
    activo,
    created_by
  )
  values (
    p_id_reserva,
    p_origen,
    case when p_origen = 'plan' then p_id_plan_adicional else null end,
    case when p_origen = 'adicional' then p_id_adicional else null end,
    trim(p_nombre),
    p_tipo_cobro,
    greatest(coalesce(p_precio_unitario, 0), 0),
    p_cantidad_personas,
    coalesce(p_aplica_todos, false),
    p_impacto_total,
    true,
    auth.uid()
  )
  returning id_reserva_plan_adicional into v_id;

  v_nuevo_total := v_total_actual + p_impacto_total;

  update public.reserva
  set valor_total = v_nuevo_total
  where id_reserva = p_id_reserva;

  return jsonb_build_object(
    'id_reserva_plan_adicional', v_id,
    'nuevo_total', v_nuevo_total
  );
exception
  when unique_violation then
    raise exception 'Este plan o adicional ya está agregado a la reserva.';
end;
$$;

create or replace function public.retirar_plan_adicional_reserva(
  p_id_reserva_plan_adicional bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item public.reserva_plan_adicional%rowtype;
  v_total_actual numeric(12,2);
  v_nuevo_total numeric(12,2);
begin
  if not exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id_rol = ur.role_id
    where ur.user_id = auth.uid()
      and r.nombre in ('administrador', 'atencion')
  ) then
    raise exception 'No autorizado para retirar planes adicionales.';
  end if;

  select *
  into v_item
  from public.reserva_plan_adicional
  where id_reserva_plan_adicional = p_id_reserva_plan_adicional
    and activo = true
  for update;

  if not found then
    raise exception 'El plan adicional ya fue retirado o no existe.';
  end if;

  select coalesce(
    r.valor_total,
    coalesce(r.precio_unitario, 0) * greatest(coalesce(r.cantidad_personas, 1), 1),
    0
  )
  into v_total_actual
  from public.reserva r
  where r.id_reserva = v_item.id_reserva
  for update;

  if not found then
    raise exception 'La reserva no existe.';
  end if;

  v_nuevo_total := greatest(0, v_total_actual - v_item.impacto_total);

  update public.reserva_plan_adicional
  set activo = false,
      removed_by = auth.uid(),
      removed_at = now()
  where id_reserva_plan_adicional = p_id_reserva_plan_adicional;

  update public.reserva
  set valor_total = v_nuevo_total
  where id_reserva = v_item.id_reserva;

  return jsonb_build_object('nuevo_total', v_nuevo_total);
end;
$$;

revoke all on function public.agregar_plan_adicional_reserva(integer,text,integer,bigint,text,text,numeric,integer,boolean,numeric) from public;
revoke all on function public.retirar_plan_adicional_reserva(bigint) from public;

grant execute on function public.agregar_plan_adicional_reserva(integer,text,integer,bigint,text,text,numeric,integer,boolean,numeric) to authenticated;
grant execute on function public.retirar_plan_adicional_reserva(bigint) to authenticated;
