-- Inventario y ventas de snacks
-- Ejecutar en Supabase SQL Editor del proyecto de pagina.admnins.

create table if not exists public.snack_producto (
  id_producto bigint generated by default as identity primary key,
  numero_producto text not null unique,
  nombre_producto text not null,
  cantidad integer not null default 0 check (cantidad >= 0),
  precio numeric(12,2) not null check (precio >= 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.snack_venta (
  id_venta bigint generated by default as identity primary key,
  fecha_venta timestamptz not null default now(),
  medio_pago text not null,
  total numeric(12,2) not null default 0 check (total >= 0),
  vendedor_user_id uuid null,
  vendedor_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.snack_venta_detalle (
  id_detalle bigint generated by default as identity primary key,
  id_venta bigint not null references public.snack_venta(id_venta) on delete cascade,
  id_producto bigint null references public.snack_producto(id_producto) on delete set null,
  numero_producto text not null,
  nombre_producto text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_snack_venta_fecha on public.snack_venta(fecha_venta);
create index if not exists idx_snack_venta_medio on public.snack_venta(medio_pago);
create index if not exists idx_snack_detalle_venta on public.snack_venta_detalle(id_venta);
create index if not exists idx_snack_producto_activo on public.snack_producto(activo);

alter table public.snack_producto enable row level security;
alter table public.snack_venta enable row level security;
alter table public.snack_venta_detalle enable row level security;

drop policy if exists snack_producto_select_auth on public.snack_producto;
create policy snack_producto_select_auth on public.snack_producto
for select to authenticated using (true);

drop policy if exists snack_producto_insert_auth on public.snack_producto;
create policy snack_producto_insert_auth on public.snack_producto
for insert to authenticated with check (true);

drop policy if exists snack_producto_update_auth on public.snack_producto;
create policy snack_producto_update_auth on public.snack_producto
for update to authenticated using (true) with check (true);

drop policy if exists snack_venta_select_auth on public.snack_venta;
create policy snack_venta_select_auth on public.snack_venta
for select to authenticated using (true);

drop policy if exists snack_detalle_select_auth on public.snack_venta_detalle;
create policy snack_detalle_select_auth on public.snack_venta_detalle
for select to authenticated using (true);

create or replace function public.registrar_venta_snack(
  p_items jsonb,
  p_medio_pago text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text := '';
  v_venta_id bigint;
  v_item jsonb;
  v_producto public.snack_producto%rowtype;
  v_producto_id bigint;
  v_cantidad integer;
  v_subtotal numeric(12,2);
  v_total numeric(12,2) := 0;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesión para registrar una venta.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta no contiene productos.';
  end if;

  if coalesce(trim(p_medio_pago), '') = '' then
    raise exception 'Selecciona un método de pago.';
  end if;

  select coalesce(email, '') into v_email
  from auth.users
  where id = v_user_id;

  insert into public.snack_venta (medio_pago, total, vendedor_user_id, vendedor_email)
  values (trim(p_medio_pago), 0, v_user_id, v_email)
  returning id_venta into v_venta_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_producto_id := nullif(v_item->>'id_producto', '')::bigint;
    v_cantidad := nullif(v_item->>'cantidad', '')::integer;

    if v_producto_id is null or v_cantidad is null or v_cantidad <= 0 then
      raise exception 'Hay un producto con cantidad inválida.';
    end if;

    select * into v_producto
    from public.snack_producto
    where id_producto = v_producto_id and activo = true
    for update;

    if not found then
      raise exception 'El producto % no existe o está inactivo.', v_producto_id;
    end if;

    if v_producto.cantidad < v_cantidad then
      raise exception 'Stock insuficiente para %. Disponible: %, solicitado: %.', v_producto.nombre_producto, v_producto.cantidad, v_cantidad;
    end if;

    v_subtotal := round(v_producto.precio * v_cantidad, 2);
    v_total := v_total + v_subtotal;

    update public.snack_producto
    set cantidad = cantidad - v_cantidad,
        updated_at = now()
    where id_producto = v_producto_id;

    insert into public.snack_venta_detalle (
      id_venta,
      id_producto,
      numero_producto,
      nombre_producto,
      cantidad,
      precio_unitario,
      subtotal
    ) values (
      v_venta_id,
      v_producto.id_producto,
      v_producto.numero_producto,
      v_producto.nombre_producto,
      v_cantidad,
      v_producto.precio,
      v_subtotal
    );
  end loop;

  update public.snack_venta
  set total = v_total
  where id_venta = v_venta_id;

  return jsonb_build_object(
    'id_venta', v_venta_id,
    'total', v_total,
    'medio_pago', trim(p_medio_pago),
    'fecha_venta', now()
  );
exception
  when others then
    raise;
end;
$$;

grant execute on function public.registrar_venta_snack(jsonb, text) to authenticated;
